# -*- coding: utf-8 -*-
"""phishing_detector.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14dhYiBhivt4mDjV-4Sktf6WCc5RJSOdZ
"""

url = input("Enter a URL: ")

score = 0

# Rule checks
if "https" not in url:
    score += 1

if any(word in url for word in ["login", "verify", "bank", "secure"]):
    score += 1

if "@" in url or "-" in url:
    score += 1

if url.count(".") > 3:
    score += 1

# Result
if score >= 2:
    print("Phishing Website Detected")
else:
    print("Safe Website")
input("Press Enter to exit...")
